### ISSUE TITLE
Getting errors while running this code in Xcode8

### ISSUE THREAD

**Issue by ghost** [openshopio/openshop.io-ios#14]
Hi 

I have installed Pods and got the following message after 

Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 32 dependencies from the Podfile and 42 total pods installed.

open OpenShop.xcworkspace
But i am getting these errors  while running this project 

diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory

/Users/harry/Downloads/openshop.io-ios-master/Pods/IDMPhotoBrowser/Classes/IDMPhoto.m:140:22: No visible @interface for 'SDWebImageManager' declares the selector 'downloadImageWithURL:options:progress:completed:'

Please let me know if i am doing something wrong ? 

Thanks

**Comment by xuanzi23** [comment]
@Mobiappsolutionz I meet this problem also. wonder why

**Comment by BluePick** [comment]
Change this block

```
            SDWebImageManager *manager = [SDWebImageManager sharedManager];
            [manager loadImageWithURL:_photoURL options:SDWebImageRetryFailed progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL) {
                CGFloat progress = ((CGFloat)receivedSize)/((CGFloat)expectedSize);
                if (self.progressUpdateBlock) {
                    self.progressUpdateBlock(progress);
                }
            } completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, SDImageCacheType cacheType, BOOL finished, NSURL * _Nullable imageURL) {
                if (image) {
                    self.underlyingImage = image;
                    [self performSelectorOnMainThread:@selector(imageLoadingComplete) withObject:nil waitUntilDone:NO];
                }
            }];
```

**Comment by abhiklodh** [comment]
Great @BluePick , works now!

**Comment by Saladaljanabi** [comment]
@abhiklodh  where did you put this block can you tell me

**Comment by Skornos** [comment]
`IDMPhotoBrowser` has a dependency on `SDWebImage` which was automatically installed with the version 4.x while the application expects the version 3.x.

This issue can be solved by putting this line in the Podfile

`pod 'SDWebImage', '~> 3.8.0'`

Sorry for the inconvenience, the latest commits are fixing the issue
