### ISSUE TITLE
http://77.93.198.186/v1.2/4/shops is not working

### ISSUE THREAD

**Issue by dhara2k17** [openshopio/openshop.io-ios#15]
It is returning internal server error code : 500

**Comment by hhkweku** [comment]
Same here; Request failed: internal server error (500)

**Comment by learnwithgabbar** [comment]
Enable to connect to server while using xcode 8

**Comment by Skornos** [comment]
Sorry for the inconvenience. The latest release is connected to the apiary mock server providing the basic functionality.
