### ISSUE TITLE
http://77.93.198.186/v1.2/4/shops returns 500 error. 

### ISSUE THREAD

**Issue by kaushik1101** [openshopio/openshop.io-ios#20]
I need to understand the json structure as there is no documentation on how to fetch data. Could you please check.

**Comment by Leo-TM** [comment]
having the same problem please guide. do we have to connect it with apiary.io ?





![screenshot-2017-08-13](https://user-images.githubusercontent.com/16442729/29246496-0a39b43e-801a-11e7-9740-fd1a9cb2d8b3.png)

**Comment by Skornos** [comment]
Sorry for the inconvenience. The latest release is connected to the apiary mock server providing the basic functionality.
