### ISSUE TITLE
Unable to build project with Xcode 8.3

### ISSUE THREAD

**Issue by ZahraShams** [openshopio/openshop.io-ios#21]
pod files dont install properly 
it may be cocoa pod version issue 
what s the solution

**Comment by NilPuig** [comment]
As another user pointed out in a comment:

Change this block

            SDWebImageManager *manager = [SDWebImageManager sharedManager];
            [manager loadImageWithURL:_photoURL options:SDWebImageRetryFailed progress:^(NSInteger receivedSize, NSInteger expectedSize, NSURL * _Nullable targetURL) {
                CGFloat progress = ((CGFloat)receivedSize)/((CGFloat)expectedSize);
                if (self.progressUpdateBlock) {
                    self.progressUpdateBlock(progress);
                }
            } completed:^(UIImage * _Nullable image, NSData * _Nullable data, NSError * _Nullable error, SDImageCacheType cacheType, BOOL finished, NSURL * _Nullable imageURL) {
                if (image) {
                    self.underlyingImage = image;
                    [self performSelectorOnMainThread:@selector(imageLoadingComplete) withObject:nil waitUntilDone:NO];
                }
            }];
