### ISSUE TITLE
http://77.93.198.186/v1.2/4/shops returns 500 server error

### ISSUE THREAD

**Issue by fengshao01** [openshopio/openshop.io-ios#23]
Since 9/27, http://77.93.198.186/v1.2/4/shops started to return 500 server error. Can someone please help, thanks.

**Comment by kassemitani** [comment]
[http://77.93.198.186/v1.2/4/shops](http://77.93.198.186/v1.2/4/shops) returns HTTP status code: **500 Internal Server Error**  !! 
Please can u share the API source-code ? [screenshot](https://pasteboard.co/GRRCAtq.png)

**Comment by KaneNguyen** [comment]
Me too,

**Comment by alien3d** [comment]
same...

**Comment by Skornos** [comment]
Sorry for the inconvenience. The latest release is connected to the apiary mock server providing the basic functionality.
