### ISSUE TITLE
90 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by come2niks** [openshopio/openshop.io-ios#5]
I have followed the same steps as mentioned and giving me this error while building the app to simulator.
1. sample error out of 90
duplicate symbol _MMRecordDebuggerKey in:
    /Users/nikhilesh/Library/Developer/Xcode/DerivedData/OpenShop-gytiskjotlrxltcmjuiuyhqsrnhq/Build/Products/Debug-iphoneos/MMRecord/libMMRecord.a(AFMMRecordSessionManagerServer.o)
    /Users/nikhilesh/Library/Developer/Xcode/DerivedData/OpenShop-gytiskjotlrxltcmjuiuyhqsrnhq/Build/Products/Debug-iphoneos/MMRecord/libMMRecord.a(MMRecord.o)

**Comment by come2niks** [comment]
It worked !!!
The was due to old version of ruby.

**Comment by Skornos** [comment]
thanks @come2niks for resolving and closing the issue.

**Comment by Skornos** [comment]
@come2niks I just ran into the same issue and tried to upgrade to ruby v2.3.1 but it didn't help. Could you elaborate more on how you resolved this? Thanks.

**Comment by come2niks** [comment]
@Skornos  
I’m using MAC OS X El Capitan with ruby version 2.3.1 

I’ve used these steps to install ruby - https://gorails.com/setup/osx/10.11-el-capitan

After the installation of ruby I followed these steps:

cd openshop.io-ios
bundle install
bundle exec fastlane build

Hope this will help.
P.S. -  Dont forgot to comment this line in pod file.
project 'OpenShop'

Thanks.

**Comment by Skornos** [comment]
Thanks, my ruby installation was broken. Now I am running 2.3.1 and the build works fine 👍

**Comment by suganyasrinivasan** [comment]
@come2niks  I followed your steps. But still facing same issue. Could you please help this to resolve...

<img width="682" alt="screen shot 2016-11-21 at 6 56 34 pm" src="https://cloud.githubusercontent.com/assets/22070138/20528035/9ea4ff10-b0f0-11e6-9fea-929fc01dce1b.png">

**Comment by Skornos** [comment]
Personally I have no output for `rails -v` because it is not installed, but my `ruby -v` output is following:

`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
`

**Comment by suganyasrinivasan** [comment]
@Skornos  from your latest commit. It's working good. Thanks a lot for your support..
