### ISSUE TITLE
Cached Images

### ISSUE THREAD

**Issue by MuhammadAmmad** [openshopio/openshop.io-ios#6]
In banners service I changed the images but url is same, means I replaced the images in directory but the app showing old images even after 1 day. Is it caching images, then how to remove it periodically or any other solution??

**Comment by Skornos** [comment]
@MuhammadAmmad are you using custom backend solution? Otherwise the banners are downloaded from our BaaS.

**Comment by MuhammadAmmad** [comment]
Yes I am using custom backend.

**Comment by Skornos** [comment]
If you reinstall the application, do you see the new images?

**Comment by MuhammadAmmad** [comment]
No, Images change after 1 or 2 days.

**Comment by Skornos** [comment]
If reinstalling the application doesn't help then the problem is not with the iOS application cache (reinstalling clears the cache).

If we change the banner image on our backend, the image in the application updates immediately.

I would double check the caching on your backend.

**Comment by MuhammadAmmad** [comment]
OK Thanks. I 'll figure it out.
