### ISSUE TITLE
90 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by suganyasrinivasan** [openshopio/openshop.io-ios#8]
I'm getting 90 duplicate symbols for architecture x86_64.

I followed the steps and installed the pod.

<img width="1392" alt="screen shot 2016-11-16 at 11 30 37 pm" src="https://cloud.githubusercontent.com/assets/22070138/20359160/9c7f8b6a-ac54-11e6-9919-017687a5b144.png">

**Comment by Skornos** [comment]
Hi @suganyasrinivasan. We've solved this issue here https://github.com/openshopio/openshop.io-ios/issues/5

**Comment by suganyasrinivasan** [comment]
I tried it again it's not solved

**Comment by Skornos** [comment]
Sorry to hear that. It took me a couple of tries also before I've managed to make it work. I remember wiping ruby off of my system and clean installing it again.

**Comment by Skornos** [comment]
@suganyasrinivasan I've just tried the clean install and bumped into the same issue. Reopening and trying to resolve.

**Comment by Skornos** [comment]
The issue is solved. Pull and install Podfile which contains post_install hook. The problem was "No common blocks" settings for MMRecord.
