### ISSUE TITLE
Conversion To Swift

### ISSUE THREAD

**Issue by MuhammadAmmad** [openshopio/openshop.io-ios#9]
@Skornos Any plan to convert it to swift?

**Comment by Skornos** [comment]
Hey, currently our focus is on different parts of the project.

**Comment by MuhammadAmmad** [comment]
OK Thanks

**Comment by aek** [comment]
Hi @Skornos 
After the latest updates on the lasts days, and with almost 2 years of difference with the last comment here, could you give us an update of the plans to support Swift and the latests IOS versions?
